### ISSUE TITLE
Dose the template support other functions of nerfstudio besides ns-train?

### ISSUE THREAD

**Issue by placeforyiming** [nerfstudio-project/nerfstudio-method-template#4]
Since only the ns-train is shown in the readme, could I know if other functions like ns-process-data / ns-viewer / ns-eval / ns-render is supposed to be seamlessly used if a new method is following this template?

Besides，dose a 3d-gs like method fit the scope of this template?

**Comment by maturk** [comment]
Yea all those work. So `ns-viewer <your-custom-method-name> --load-config PATH` and other similar commands work just like they do for nerfacto and others.
